### ISSUE TITLE
Accessing AST?

### ISSUE THREAD

**Issue by archywillhe** [facebookincubator/Glean#345]
Do Angel or any toolkit in Glean provide ways to view the full AST (e.g of a function) after I get a queried fact? 

What's the best way to build such pipeline? (e.g. accessing AST, walking it to mutate parts of existing code)

**Comment by simonmar** [comment]
Glean stores data for each language according to its schema; see for example the schema for C++ [here](https://github.com/facebookincubator/Glean/blob/main/glean/schema/source/cxx.angle). The schema doesn't normally encode the full AST, because it would be a lot of data and make indexing and querying much slower.

If you want to operate on the full AST, you would have to define a schema for that for the language you're interested in, and build an indexer too. But I'm concerned about the word "mutate" in your question: Glean is for querying, not modifying.
