### ISSUE TITLE
Please keep the builds clean

### ISSUE THREAD

**Issue by nnWhisperer** [facebookincubator/Glean#465]
Hello,
Thank you for the great work. I appreciate this treasure project. I tried and did manage to build it myself, after spending some time but, for a project of this importance I believe that there must be an easy way to get started without fighting against the build errors. Thank you

**Comment by simonmar** [comment]
Thanks for the feedback. As with hsthrift we do also have an internal CI that keeps the build working, but it doesn't run all the tests for the external indexers, and that's why we see regressions in these tests on github CI. The build should be fine, it's just test failures and usually we just need to update the sample test output. But obviously we'd like to keep the CI green.

I'll leave the issue open until we fix the current test failures.
